### ISSUE TITLE
This data disappeares repeatedly

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia-staking-ui#12]
![Image](https://user-images.githubusercontent.com/1608576/220829047-5ae31c0b-8d07-488a-979b-f42c2cd53106.png)

![Image](https://user-images.githubusercontent.com/1608576/220829185-33cd2d4e-3a4a-41bc-9aaf-8032ef485ff8.png)

**Comment by 1022ranji** [comment]
I'm not sure to understand what you mean, could you please explain in more detail?

**Comment by wuminzhe** [comment]
yesterday, after I open this page, the content in my screenshots was changing to each other repeatedly.

**Comment by wuminzhe** [comment]
I didn't see this problem today.
