### ISSUE TITLE
Total staked power issue

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia-staking-ui#22]
The total staked power in the collator list window is not equal to the power in the `Staking delegation` list. 

Is this a bug? @1022ranji @isunaslabs @hackfisher 

<img width="836" alt="image (12)" src="https://user-images.githubusercontent.com/1608576/224667255-c056fdf6-ea02-4068-9997-00cf4d935a3c.png">
<img width="817" alt="Snipaste_2023-03-11_09-02-33 (1)" src="https://user-images.githubusercontent.com/1608576/224667269-b65afe78-b061-40f0-a694-956397f59933.png">

**Comment by isunaslabs** [comment]
@wuminzhe There isn't an API that shows the staked power for the collators in the waiting pool, the current API only contains the staked power for the active collators.
