### ISSUE TITLE
The deposit ID#0 is due but the progress bar is still moving forward.

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/darwinia-staking-ui#25]
<img width="576" alt="image" src="https://user-images.githubusercontent.com/80877629/226543612-715783c2-c272-477c-8524-8784e3251da5.png">

**Comment by 1022ranji** [comment]
At the same time, deposit ID#0 is due but the UI shows "Withdraw earlier", need to check and change it to "Withdraw". @isunaslabs 
<img width="541" alt="image" src="https://user-images.githubusercontent.com/80877629/226544282-137a2ad7-6647-41f7-9ba9-912432568fce.png">

**Comment by isunaslabs** [comment]
Seen. Please give me the account address that you've used to generate this bug

**Comment by 1022ranji** [comment]
0xAe0222eA1c24c3579b4CC751a2BE757aBeDFD78E
