### ISSUE TITLE
multisig contract accounts how to query and use staking since metamask do not support

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia-staking-ui#31]

**Comment by hackfisher** [comment]
Can we support wallet connect and Gnosis Safe?

For Gnosis Multisig, may need to encode data before unstake and withraw deposit

**Comment by 1022ranji** [comment]
UI please refer to: https://www.figma.com/file/Ks4SJYuOsXTW2rVDLBbB3r/APPS?node-id=6292%3A23105&t=qCSOn3Hx4iMm8ECd-1
<img width="869" alt="image" src="https://user-images.githubusercontent.com/80877629/236104604-9032ab9d-c576-4654-b780-d4a1c77bba86.png">
