### ISSUE TITLE
minor updates

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/darwinia-staking-ui#62]
https://www.notion.so/darwinia/Update-Staking-Dapp-Minor-Update-3bf4c6e44d3442fe9067aae9a9bd71b5

**Comment by JayJay1024** [comment]
https://github.com/polkadot-js/apps/pull/9868

<img width="392" alt="image" src="https://github.com/darwinia-network/darwinia-staking-ui/assets/21007682/5ed92dbb-9ede-456a-8a15-fc461a1f700f">

<img width="397" alt="image" src="https://github.com/darwinia-network/darwinia-staking-ui/assets/21007682/0260203d-5288-4bf9-ab2c-ceaf9cf8ea4d">
